apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "cert-policy.example.com"
webhooks:
- name: "cert-policy.example.com"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["secrets"]
    scope:       "Cluster"
  clientConfig:
    service:
      namespace: "trezlabs"
      name: "trezlabs-admission"
    caBundle: $CERT
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5