namespace: trezlabs

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: certificates
    type: "kubernetes.io/tls"
    files:
    - ./certs/ca.crt
    - ./certs/tls.crt
    - ./certs/tls.key
    